name: pages-maintenance
on:
  push:
    branches: [ "main" ]
    paths:
      - 'category/**.html'
      - 'category/**/**.html'
      - 'index.html'
      - 'assets/**'
      - '.github/workflows/pages-maintenance.yml'
jobs:
  build-meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate sitemap.xml
        run: |
          SITE="${{ vars.SITE_URL || 'https://parksy.kr' }}"
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          while IFS= read -r f; do
            url="${f#./}"
            [[ "$url" == assets/* ]] && continue
            [[ "$url" == 404.html ]] && continue
            if [[ "$url" == */index.html ]]; then url="${url%index.html}"; fi
            echo "  <url><loc>${SITE}/${url}</loc></url>" >> sitemap.xml
          done < <(find . -type f -name "*.html" | sort)
          echo '</urlset>' >> sitemap.xml

      - name: Rebuild category indexes (latest first)
        run: |
          set -e
          for d in category/system-configuration \
                   category/writers-path \
                   category/blog-transformation \
                   category/device-chronicles \
                   category/webappsbook-codex \
                   category/webappsbookcast \
                   category/thought-archaeology; do
            [[ -d "$d" ]] || continue
            LIST=$(find "$d" -maxdepth 1 -type f -name "*.html" ! -name "index.html" | sort -r)
            [[ -f "$d/index.html" ]] || continue
            awk -v list="$LIST" '
              /<ul id="post-list">/ {
                print; 
                while ( ( "echo \"" list "\" " | getline line ) > 0 ) {
                  gsub(/^\.\//,"",line)
                  cmd="basename \"" line "\""; cmd | getline base; close(cmd)
                  date=substr(base,1,10)
                  title=base
                  sub(/^[0-9]{4}-[0-9]{2}-[0-9]{2}-/,"",title)
                  sub(/\.html$/,"",title)
                  gsub(/-/," ",title)
                  printf("        <li><a href=\"/%s\">[%s] %s</a></li>\n", line, date, title)
                }
                skip=1; next
              }
              { print }
            ' "$d/index.html" > "$d/index.tmp" && mv "$d/index.tmp" "$d/index.html"
          done

      - name: Commit sitemap & index updates
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add sitemap.xml category/*/index.html || true
          git diff --cached --quiet || git commit -m "ci: rebuild sitemap & category indexes"
          git push